print("Please enter number of coins: ")
num_of_quarters = int(input("# of quarters:"))
num_of_dimes = int(input("# of dimes:"))
num_of_nickels = int(input("# of nickels:"))
num_of_pennies = int(input("# of pennies:"))
Total_Amount = ((num_of_quarters*25) + (num_of_dimes*10) + (num_of_nickels*5) + num_of_pennies)
dollar = int(Total_Amount// 100)
cents = int (dollar%100)
print("The total is", dollar, " dollars and ",cents,"cents")
